name: RadishDB CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build-tag-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install compiler
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Clean build
        run: make clean || true

      - name: Build
        run: make

      - name: Run binary
        run: ./main || true

      - name: Generate tag
        id: tag
        run: |
          TAG=v$(date +'%Y.%m.%d.%H%M%S')
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
        env:
          GITHUB_TOKEN: ${{ Docker.secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ Docker.secrets.DOCKER_USERNAME }}
          password: ${{ Docker.secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ Docker.secrets.DOCKER_USERNAME }}/radishdb:${{ env.TAG }} .

      - name: Push Docker image
        run: docker push ${{ Docker.secrets.DOCKER_USERNAME }}/radishdb:${{ env.TAG }}

      - name: Run container
        run: docker run --rm ${{ Docker.secrets.DOCKER_USERNAME }}/radishdb:${{ env.TAG }}
